@url = http://localhost:8080/app
@api = http://localhost:8080/app/api
@sesionAdmin = e4sf3ch3jrkj0ln17hmd6mdc8e
@sesionHacker = 585722f60e632f41061a99f613724d37

###
GET {{api}}/perfil
Cookie: PHPSESSID={{sesionAdmin}}

###
POST {{url}}/ingresar
Content-type: application/json

{
  "cedula": 12345678,
  "clave": "Admin.123"
}

###
POST {{api}}/registrarse
Content-type: application/json

{
  "idCard": 28072391,
  "password": "Fran.123",
  "secret_question": "Color favorito",
  "secret_answer": "vinotinto"
}

###
GET {{api}}/clientes
Cookie: PHPSESSID={{sesionHacker}}

###
GET {{api}}/clientes/15

###
POST {{api}}/clientes
Content-type: application/json

{
  "cedula": 28072391,
  "nombres": "Franyer",
  "apellidos": "Sánchez",
  "telefono": "+58 416-5335826",
  "id_localidad": 523,
  "id_sector": 1
}

###
PATCH {{api}}/clientes/11
Content-type: application/json

{
  "nombres": "Franyer",
  "apellidos": "Sánchez",
  "telefono": "+58 416-5335826",
  "id_sector": 1
}

###
DELETE {{api}}/clientes/1
