@url = http://localhost:8080/app

###
GET {{url}}/api/perfil
Cookie: PHPSESSID=e4sf3ch3jrkj0ln17hmd6mdc8e

###
POST {{url}}/ingresar
Content-type: application/json

{
  "cedula": 12345678,
  "clave": "Admin.123"
}

###
POST {{url}}/api/registrarse
Content-type: application/json

{
  "idCard": 28072391,
  "password": "Fran.123",
  "secret_question": "Color favorito",
  "secret_answer": "vinotinto"
}
