<?php

namespace SITCAV\Enums;

enum ClaveSesion
{
  case UI_TEMA;
  case UI_COLORES;
  case UI_DIRECCION;
  case UI_POSICION_MENU_NAVEGACION;
  case UI_ANCHURA;
  case UI_TIPO_MENU_NAVEGACION;
  case UI_TIPO_TARJETAS;
  case MENSAJES_ERRORES;
  case MENSAJES_EXITOS;
  case MENSAJES_ADVERTENCIAS;
  case MENSAJES_INFORMACIONES;
  case OAUTH2_ESTADO;
  case OAUTH2_TOKEN;
  case USUARIO_ID;
  case USUARIO_CORREO;
  case CODIGO_VERIFICACION;
  case CODIGO_VERIFICACION_EXPIRACION;
}
