<?php

namespace SITCAV\Enums;

enum Permiso
{
  case DEGRADAR_EMPLEADO_SUPERIOR;
  case DESPEDIR_EMPLEADO;
  case EDITAR_DATOS_DEL_NEGOCIO;
  case EDITAR_PERFIL;
  case GENERAR_FACTURA;
  case PROMOVER_VENDEDOR;
  case REALIZAR_VENTA;
  case RECONTRATAR_EMPLEADO;
  case REGISTRAR_CATEGORIA;
  case REGISTRAR_CLIENTE;
  case REGISTRAR_COMPRA;
  case REGISTRAR_COTIZACION;
  case REGISTRAR_EMPLEADO;
  case REGISTRAR_PAGO;
  case REGISTRAR_PRODUCTO;
  case REGISTRAR_PROVEEDOR;
  case RESPALDAR_BASE_DE_DATOS;
  case RESTAURAR_BASE_DE_DATOS;
  case VER_CLIENTES;
  case VER_COMPRAS;
  case VER_EMPLEADOS;
  case VER_NEGOCIOS;
  case VER_PAGOS;
  case VER_PRODUCTOS;
  case VER_PROVEEDORES;
  case VER_VENTAS;
  case VER_DETALLES_EMPLEADO;
  case RESTABLECER_CLAVE_EMPLEADO;
}
